wandb_version: 1

subsample:
  desc: null
  value: 0.6666666666666666
scale_pos_weight:
  desc: null
  value: 1.0
reg_lambda:
  desc: null
  value: 0.21544346900318823
reg_alpha:
  desc: null
  value: 1.0
n_estimators:
  desc: null
  value: 300
min_child_weight:
  desc: null
  value: 1
max_depth:
  desc: null
  value: 12
learning_rate:
  desc: null
  value: 0.4212105263157895
gamma:
  desc: null
  value: 0.5263157894736842
colsample_bytree:
  desc: null
  value: 0.7222222222222222
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.7
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1725888601
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.12.4
      5: 0.17.7
      8:
      - 1
      - 5
      13: darwin-x86_64
