wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.7
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1725546854
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      3:
      - 23
      4: 3.12.4
      5: 0.17.7
      8:
      - 1
      - 5
      13: darwin-x86_64
